import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {Model} from 'survey-core';
import {createSession} from '../runtime/session.js';
const read=f=>JSON.parse(readFileSync(new URL(f,import.meta.url)));
const manifest=read('../curriculum/course-manifest.json');
const memory=()=>{const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k),m};};
let serial=0;
function start(lesson,storage=memory(),events=[]){return createSession({lesson,Model,storage,uuid:()=>`test-${++serial}`,now:()=> '2026-10-05T00:00:00.000Z',dispatch:e=>events.push(e)});}
function fill(s,lesson){for(const id of lesson.coreActivityIds){const q=s.survey.getQuestionByName(id);s.survey.setValue(id,q.correctAnswer);}for(const q of s.survey.getAllQuestions().filter(q=>q.getType()==='comment'))s.survey.setValue(q.name,'I compared the supplied evidence, tested the result against clear criteria, and would check the relevant source before deciding.');}
test('15 complete drafts, three parts, unique stable IDs, sources and actionable feedback',()=>{assert.equal(manifest.lessons.length,15);assert.deepEqual(manifest.parts.map(p=>p.lessons.length),[5,5,5]);const ids=new Set();for(const l of manifest.lessons){assert.ok(l.objective&&l.explanation&&l.scenario&&l.uncertainty);assert.equal(l.activities.length,2);assert.ok(l.transfer.rubric.length>=3);for(const id of [l.id,l.transfer.id,...l.activities.map(a=>a.id)]){assert.ok(!ids.has(id));ids.add(id);}for(const a of l.activities){assert.ok(a.choices.some(c=>c.value===a.correctAnswer));assert.ok(a.choices.every(c=>c.feedback.length>20));}for(const id of l.sourceIds)assert.ok(manifest.sources.some(s=>s.id===id));}});
for(let n=1;n<=15;n++){
 const lesson=read(`../lessons/course-${String(n).padStart(2,'0')}.json`),authored=manifest.lessons[n-1];
 test(`L${n}: runtime choices, answers and feedback match manifest`,()=>{const s=start(lesson);for(const a of [...authored.activities,...(authored.branchActivity?[authored.branchActivity]:[])]){const q=s.survey.getQuestionByName(a.id);assert.equal(q.correctAnswer,a.correctAnswer);for(const c of a.choices){s.survey.setValue(a.id,c.value);const f=s.survey.getQuestionByName(a.id+'.feedback.'+c.value);assert.ok(f.html.includes(c.feedback.replaceAll('&','&amp;').replaceAll('“','“'))||f.html.includes(c.feedback));assert.equal(f.visibleIf,`{${a.id}} = '${c.value}'`);}}});
 if(authored.branchActivity)test(`L${n}: branch appears only for detour path and cleared branch is excluded`,()=>{const s=start(lesson),b=authored.branchActivity,q=s.survey.getQuestionByName(b.visibleIfActivity);s.survey.setValue(q.name,q.choices.find(c=>c.value!==b.visibleIfNotEqual).value);assert.equal(s.survey.pages.find(p=>p.name==='detour').isVisible,true);s.survey.setValue(b.id,b.correctAnswer);s.survey.setValue(q.name,b.visibleIfNotEqual);assert.equal(s.survey.pages.find(p=>p.name==='detour').isVisible,false);assert.equal(s.survey.getValue(b.id),undefined);});
 test(`L${n}: missing work and whitespace cannot complete; full work can`,()=>{const events=[],s=start(lesson,memory(),events);assert.equal(s.complete(),false);fill(s,lesson);s.survey.setValue(lesson.reflectionId,' '.repeat(45));assert.equal(s.complete(),false);s.survey.setValue(lesson.reflectionId,'I would check the evidence and explain my independent decision.');assert.equal(s.complete(),true);assert.equal(s.result().score,2);assert.equal(events.filter(e=>e.type==='completed').length,1);s.complete();assert.equal(events.filter(e=>e.type==='completed').length,1);});
 if(authored.branchActivity)test(`L${n}: selected detour requires its answer, but wrong answers do not block learning`,()=>{const s=start(lesson),b=authored.branchActivity;fill(s,lesson);const q=s.survey.getQuestionByName(b.visibleIfActivity);s.survey.setValue(q.name,q.choices.find(c=>c.value!==b.visibleIfNotEqual).value);assert.equal(s.complete(),false);s.survey.setValue(b.id,b.choices.find(c=>c.value!==b.correctAnswer).value);assert.equal(s.complete(),true);assert.equal(s.result().score,1);});
 test(`L${n}: partial answers/page and completed state resume, restart creates new attempt`,()=>{const storage=memory(),s=start(lesson,storage);s.survey.setValue(lesson.coreActivityIds[0],s.survey.getQuestionByName(lesson.coreActivityIds[0]).correctAnswer);s.survey.currentPage=s.survey.pages.find(p=>p.name==='decide');const restored=start(lesson,storage);assert.equal(restored.resumed,true);assert.equal(restored.survey.currentPage.name,'decide');assert.equal(restored.survey.data[lesson.coreActivityIds[0]],s.survey.data[lesson.coreActivityIds[0]]);fill(restored,lesson);restored.complete();const done=start(lesson,storage);assert.equal(done.state.completed,true);const prior=done.state.attemptId;assert.equal(done.restart(),true);const fresh=start(lesson,storage);assert.notEqual(fresh.state.attemptId,prior);assert.deepEqual(fresh.survey.data,{});assert.equal(fresh.state.completed,false);});
}
test('lesson storage isolated; malformed or incomplete completion does not bypass requirements',()=>{const a=read('../lessons/course-01.json'),b=read('../lessons/course-02.json'),store=memory(),s=start(a,store);fill(s,a);s.complete();const other=start(b,store);assert.deepEqual(other.survey.data,{});assert.notEqual(s.key,other.key);const bad=JSON.parse(store.getItem(s.key));bad.answers={};bad.completed=true;store.setItem(s.key,JSON.stringify(bad));assert.equal(start(a,store).state.completed,false);store.setItem(s.key,'not json');assert.equal(start(a,store).resumed,false);});
test('storage failures keep activity usable and do not claim reset succeeded',()=>{const lesson=read('../lessons/course-01.json'),storage={getItem(){throw Error()},setItem(){throw Error()},removeItem(){throw Error()}},s=start(lesson,storage);fill(s,lesson);assert.equal(s.complete(),true);assert.equal(s.storageWorks,false);assert.equal(s.restart(),false);});
test('event contract excludes free-text answer contents and bounds diagnostic history',()=>{const lesson=read('../lessons/course-01.json'),events=[],s=start(lesson,memory(),events);const value='Private practice string should stay out of emitted event payloads.';s.survey.setValue(lesson.reflectionId,value);for(let i=0;i<105;i++)s.survey.setValue(lesson.reflectionId,value+i);assert.ok(!JSON.stringify(events).includes(value));assert.equal(s.state.events.length,100);for(const e of events){assert.equal(e.schemaVersion,1);assert.equal(e.lessonId,lesson.id);assert.ok(e.eventId&&e.attemptId&&e.timestamp);}});
for(let n=1;n<=15;n++){
 const lesson=read(`../lessons/course-${String(n).padStart(2,'0')}.json`),authored=manifest.lessons[n-1];
 test(`L${n}: SurveyJS navigation validates pages and completes the actual model`,()=>{const s=start(lesson);assert.equal(s.survey.nextPage(),false);for(const id of lesson.coreActivityIds)s.survey.setValue(id,s.survey.getQuestionByName(id).correctAnswer);assert.equal(s.survey.nextPage(),true);assert.equal(s.survey.currentPage.name,'decide');assert.equal(s.survey.nextPage(),true);assert.equal(s.survey.currentPage.name,'transfer');s.survey.tryComplete();assert.equal(s.state.completed,false);fill(s,lesson);s.survey.tryComplete();assert.equal(s.survey.isCompleted,true);assert.equal(s.state.completed,true);});
 test(`L${n}: only selected feedback is visible`,()=>{const s=start(lesson);for(const a of authored.activities){for(const c of a.choices){s.survey.setValue(a.id,c.value);for(const other of a.choices)assert.equal(s.survey.getQuestionByName(a.id+'.feedback.'+other.value).isVisible,other.value===c.value);}}});
}

test('versioned persistence separates incompatible lessons and rejects wrong-version records',()=>{const lesson=read('../lessons/course-01.json'),storage=memory(),s=start(lesson,storage);fill(s,lesson);s.complete();const newer={...lesson,version:lesson.version+1},v2=start(newer,storage);assert.notEqual(s.key,v2.key);assert.deepEqual(v2.survey.data,{});v2.restart();assert.equal(start(lesson,storage).state.completed,true);const bad=JSON.parse(storage.getItem(s.key));bad.lessonVersion=99;storage.setItem(s.key,JSON.stringify(bad));assert.equal(start(lesson,storage).resumed,false);});
for(const n of [14,15])test(`L${n}: every project submission is required and length limits enforced`,()=>{const lesson=read(`../lessons/course-${n}.json`),s=start(lesson);fill(s,lesson);const fields=s.survey.getAllQuestions().filter(q=>q.getType()==='comment');assert.equal(fields.length,4);for(const q of fields){const value=q.value;s.survey.setValue(q.name,'');assert.equal(s.complete(),false);s.survey.setValue(q.name,' '.repeat(100));assert.equal(s.complete(),false);s.survey.setValue(q.name,'x'.repeat(q.maxLength+1));assert.equal(s.complete(),false);s.survey.setValue(q.name,value);}assert.equal(s.complete(),true);assert.equal(lesson.completionPolicy.reflectionSemanticallyGraded,false);});
test('all runtime schemas have declared stable IDs and formative completion metadata',()=>{for(let n=1;n<=15;n++){const l=read(`../lessons/course-${String(n).padStart(2,'0')}.json`),s=start(l);assert.equal(manifest.lessons[n-1].status,'implemented-draft');assert.equal(l.version,1);assert.equal(l.completionPolicy.correctAnswersRequired,false);const inputs=s.survey.getAllQuestions().filter(q=>q.getType()!=='html').map(q=>q.name);assert.deepEqual([...inputs].sort(),[...l.activityIds].sort());assert.equal(new Set(inputs).size,inputs.length);}});
