"""Build course.js (the site's course data) from the review package.

Source of truth: content/review-package/curriculum/course-manifest.json plus the SurveyJS
lesson files in content/review-package/lessons/. Edit the package (its build_course.py), copy it
here, then run: python3 tools/build_course.py
The site renders these lessons with its own player; SurveyJS itself is not loaded.
"""
import html, json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
PKG = ROOT / 'content' / 'review-package'
m = json.loads((PKG / 'curriculum' / 'course-manifest.json').read_text())

SHORT = {1: 'Understand', 2: 'Revise', 3: 'Judgment'}
LINES = {1: 'What AI is doing, and how to point it at a useful result.',
         2: 'Treat the first answer as a draft, then test it and improve it.',
         3: 'Bring the right material, stay in charge, and make something real.'}
strip = lambda h: re.sub(r'\s+', ' ', html.unescape(re.sub(r'<[^>]+>', ' ', h or ''))).strip()

def choice(a, kind, title):
    return {'kind': kind, 'id': a['id'], 'title': title, 'prompt': a['prompt'], 'choices': a['choices'],
            'correct': a['correctAnswer'], 'rationale': a.get('rationale', '')}

parts = [{'id': p['id'], 'num': p['number'], 'name': p['title'], 'short': SHORT[p['number']], 'line': LINES[p['number']]} for p in m['parts']]
lessons = []
for l in m['lessons']:
    survey = json.loads((PKG / 'lessons' / f"course-{l['number']:02d}.json").read_text())['survey']
    tpage = next(p for p in survey['pages'] if p['name'] == 'transfer')
    fields, note = [], ''
    for e in tpage['elements']:
        if e['type'] == 'comment':
            mins = [v.get('minLength', 0) for v in e.get('validators', []) if v.get('type') == 'text']
            fields.append({'id': e['name'], 'label': e['title'], 'min': max(mins or [30]), 'max': e.get('maxLength', 2000)})
        elif e['type'] == 'html' and e['name'].endswith('.rubric'):
            note = strip(e['html'].split('</ul>', 1)[1]) if '</ul>' in e['html'] else ''
    a1, a2 = l['activities']
    steps = [
        {'kind': 'learn', 'id': f"{l['id']}.understand", 'title': 'What to know', 'objective': l['objective'], 'body': l['explanation'], 'scenario': l['scenario']},
        choice(a1, 'choice', a1['prompt']),
        choice(a2, 'choice', a2['prompt']),
        {'kind': 'transfer', 'id': l['transfer']['id'], 'title': 'Make it yours', 'fields': fields, 'rubric': l['transfer']['rubric'], 'note': note},
    ]
    out = {'id': l['id'], 'version': l['version'], 'num': l['number'], 'arc': m['parts'][l['part'] - 1]['title'],
           'title': l['title'], 'q': l['objective'], 'blurb': l['scenario'], 'min': l['estimatedMinutes'], 'steps': steps}
    b = l.get('branchActivity')
    if b:
        d = choice(b, 'detour', 'Take a closer look')
        d['when'] = {'id': b['visibleIfActivity'], 'notEqual': b['visibleIfNotEqual']}
        out['detour'] = d
    lessons.append(out)

head = f"/* Generated by tools/build_course.py from the review package ({m['contentVersion']}). Do not edit by hand. */\n"
js = head + f"window.LAI_COURSE_META = {json.dumps({'courseId': m['courseId'], 'contentVersion': m['contentVersion'], 'status': m['status']})};\n"
js += f"window.LAI_PARTS = {json.dumps(parts, ensure_ascii=False, indent=1)};\n"
js += f"window.LAI_COURSE = {json.dumps(lessons, ensure_ascii=False, indent=1)};\n"
(ROOT / 'course.js').write_text(js)
print(f"course.js: {len(lessons)} lessons, {sum(1 for x in lessons if 'detour' in x)} detours, {sum(len(x['steps'][3]['fields']) for x in lessons)} transfer fields")
